### ISSUE TITLE
how can i use it ??

### ISSUE THREAD

**Issue by sult4n94** [goronfreeman/fine-bros-countdown#1]
i try it in my host but nothing is working 

** 
thanks in advance .

**Comment by goronfreeman** [comment]
To view it, go [here](http://goronfreeman.github.io/fine-bros-countdown/). If you want to run it locally:

1) `git clone git@github.com:goronfreeman/fine-bros-countdown.git`
2) `cd fine-bros-countdown`
3) `npm install && npm install gulp` (you'll need [npm](https://docs.npmjs.com/getting-started/installing-node) installed if you don't already)
4) `gulp`
5) Go to localhost:8080 in your browser.
